server:
  port: 8081
#端口号与 vue应用下的config目录下的 dev.env.js中的BaseApi的端口号一致
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring_mall?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
  resources:
    static-locations: classpath:static
pagehelper:
  auto-dialect: mysql
logging:
  level:
    com.cskaoyan.mapper: debug
